Repository code-gambit/VT-WebClient, pull requests merged in 2021-06, with the labels that each got.

#48 File upload status
  src/Components/Screens/FileDetail.js
  src/Components/Screens/FileForm.js
  src/Components/Screens/Files.js
Labels: Status: Review Needed

#49 Code splitting and error boundary
  src/App.css
  src/Components/ErrorBoundary.js
  src/Components/Loading.js
  src/Components/Screens/FileDetail.js
  src/Components/Screens/Files.js
  src/Components/Screens/URL.js
  src/Routing.js
  src/index.css
  src/index.js
Labels: Status: Review Needed

#60 Resolved empty URL redirects, file_size handling and file details redirection
  src/Components/Screens/FileDetail.js
  src/Components/Screens/FileForm.js
  src/Components/Screens/RenderFile.js
  src/Components/Screens/URL.js
  src/Components/URLSearchBar.js
  src/utils/fileSize.js
Labels: Status: Review Needed

#61 Added date filter attributes and resolved routing issue
  src/Components/Screens/FileDateFilter.js
  src/Components/Screens/Files.js
  src/Routing.js
Labels: Status: Review Needed

#63 Optimized rendering
  package-lock.json
  package.json
  src/Components/Loading.js
  src/Components/Screens/FileDateFilter.js
  src/Components/Screens/FileDetail.js
  src/Components/Screens/FileForm.js
  src/Components/Screens/Files.js
  src/Components/Screens/RenderFile.js
  src/Components/Screens/URL.js
  src/index.js
  src/wdyr.js
Labels: Status: Review Needed

#64 fixed footer component
  src/Components/Footer.js
Labels: Status: In Progress

#67 File cards Updated
  src/Components/FileDelete.js
  src/Components/FileShare.js
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/Screens/FileForm.js
  src/Components/Screens/Files.js
  src/Components/Screens/RenderFile.js
  src/Routing.js
  src/index.css
  src/utils/fileIcon.js
  src/utils/fileType.js
Labels: Status: Review Needed, Type: Enhancement

#72 Modularized file details component
  src/Components/FileShare.js
  src/Components/Screens/FileDetail.js
  src/Components/Screens/FileForm.js
  src/Components/Screens/RenderFile.js
  src/Components/Screens/URL.js
  src/Routing.js
  src/index.css
  src/utils/getDate.js
Labels: Status: Review Needed

#71 Refactored auth components
  src/Components/Auth/ForgotPassword.js
  src/Components/Auth/SignIn.js
  src/Components/Auth/SignUp.js
  src/Components/Screens/Authentication.js
  src/Components/Screens/SignUp.js
  src/Routing.js
Labels: Status: In Progress, UI

#75 Made URL card responsive and refactored project directory
  src/App.js
  src/Components/AuthComponents/ChangeName.js
  src/Components/AuthComponents/ChangePassword.js
  src/Components/AuthComponents/ForgotPassword.js
  src/Components/AuthComponents/SignIn.js
  src/Components/AuthComponents/SignUp.js
  src/Components/FileComponents/FileCard.js
  src/Components/FileComponents/FileDateFilter.js
  src/Components/FileComponents/FileDelete.js
  src/Components/FileComponents/FileForm.js
  src/Components/FileComponents/FileShare.js
  src/Components/FileComponents/URLCard.js
  src/Components/Footer.js
  src/Components/Screens/Authentication.js
  src/Components/Screens/ErrorBoundary.js
  src/Components/Screens/FileDetail.js
  src/Components/Screens/FileList.js
  src/Routing.js
Labels: Status: Review Needed

#76 Created Readme File
  README.md
Labels: Status: Review Needed
